-- Rollback: see bottom of file. Forward migration is additive; no data loss on rollback
-- aside from the new GarageSpot rows and the defaultFreeGarageSpots column.
-- Note: the enum additions in 20260520120000_garage_spots_enums are NOT reversible
-- without enum recreation + re-cast even if this file is rolled back.

-- ── 1. New columns on existing tables ─────────────────────────────────────
ALTER TABLE "Product"
  ADD COLUMN "visibleInStore" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "virtual"        BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX "Product_visibleInStore_status_idx" ON "Product"("visibleInStore", "status");

ALTER TABLE "GeneralSettings"
  ADD COLUMN "defaultFreeGarageSpots" INTEGER;

-- ── 2. GarageSpot table ───────────────────────────────────────────────────
CREATE TABLE "GarageSpot" (
    "id"                TEXT             NOT NULL,
    "userId"            TEXT             NOT NULL,
    "tier"              "GarageSpotTier" NOT NULL DEFAULT 'free',
    "source"            "GarageSpotSource" NOT NULL,
    "carId"             TEXT,
    "sourceOrderItemId" TEXT,
    "createdAt"         TIMESTAMP(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"         TIMESTAMP(3)     NOT NULL,
    CONSTRAINT "GarageSpot_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "GarageSpot_carId_key"             ON "GarageSpot"("carId");
CREATE UNIQUE INDEX "GarageSpot_sourceOrderItemId_key" ON "GarageSpot"("sourceOrderItemId");
CREATE        INDEX "GarageSpot_userId_idx"            ON "GarageSpot"("userId");
CREATE        INDEX "GarageSpot_userId_tier_idx"       ON "GarageSpot"("userId", "tier");
CREATE        INDEX "GarageSpot_userId_carId_idx"      ON "GarageSpot"("userId", "carId");

ALTER TABLE "GarageSpot"
  ADD CONSTRAINT "GarageSpot_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "GarageSpot"
  ADD CONSTRAINT "GarageSpot_carId_fkey"
  FOREIGN KEY ("carId") REFERENCES "Car"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ── 3. Backfill ───────────────────────────────────────────────────────────
-- When no GeneralSettings row exists yet: default_free = 1 (no row to update).
-- When a GeneralSettings row exists, "defaultFreeGarageSpots IS NULL" at migration
-- time means "column was just added, never set" — coerce to the documented default
-- of 1 (master plan §3 point 1). Post-migration, admin-set NULL = unlimited and is
-- handled by runtime reconciliation (TASK-B), not by this one-shot migration.
DO $$
DECLARE
  default_free INT := 1;
  current_setting INT;
  has_settings_row BOOLEAN;
BEGIN
  -- Coerce legacy NULL (column just added) to the documented default of 1.
  -- Idempotent: subsequent re-runs find nothing to update.
  UPDATE "GeneralSettings"
    SET "defaultFreeGarageSpots" = 1
    WHERE "defaultFreeGarageSpots" IS NULL;

  SELECT COUNT(*) > 0 INTO has_settings_row FROM "GeneralSettings";

  IF has_settings_row THEN
    SELECT "defaultFreeGarageSpots" INTO current_setting FROM "GeneralSettings" ORDER BY "createdAt" ASC LIMIT 1;
    IF current_setting IS NULL THEN
      -- Defensive only: the UPDATE above eliminates this branch in the migration's
      -- single run. Kept so re-running the DO block manually (tests) stays correct
      -- if the row was nulled out between runs — admin-set NULL = unlimited backfill.
      default_free := 0;
    ELSE
      default_free := current_setting;
    END IF;
  END IF;

  -- 3a. One free spot per existing Car. cuid()-style ids are generated by application code,
  -- but in-SQL we need a stable id; use a deterministic prefix + Car.id to keep the row
  -- idempotency-recoverable. Length stays under VARCHAR limits (Car.id is cuid, ~25 chars).
  INSERT INTO "GarageSpot" ("id", "userId", "tier", "source", "carId", "createdAt", "updatedAt")
  SELECT
    'gs_bf_' || c."id",
    c."userId",
    'free'::"GarageSpotTier",
    'default_free'::"GarageSpotSource",
    c."id",
    NOW(),
    NOW()
  FROM "Car" c
  WHERE NOT EXISTS (SELECT 1 FROM "GarageSpot" gs WHERE gs."carId" = c."id");

  -- 3b. For users with zero cars, give them min(default_free, 1) empty free spots.
  -- Spec: §3 migration backfill point 3. If default_free is 0 (unlimited or admin pre-set), insert nothing.
  IF default_free >= 1 THEN
    INSERT INTO "GarageSpot" ("id", "userId", "tier", "source", "carId", "createdAt", "updatedAt")
    SELECT
      'gs_bfempty_' || u."id",
      u."id",
      'free'::"GarageSpotTier",
      'default_free'::"GarageSpotSource",
      NULL,
      NOW(),
      NOW()
    FROM "User" u
    WHERE NOT EXISTS (SELECT 1 FROM "Car" c WHERE c."userId" = u."id")
      AND NOT EXISTS (
        SELECT 1 FROM "GarageSpot" gs
        WHERE gs."userId" = u."id" AND gs."carId" IS NULL AND gs."tier" = 'free'
      );
  END IF;

  -- 3c. AdminAudit entry recording the batch. Singleton entry per migration run.
  INSERT INTO "AdminAudit" ("id", "actorId", "action", "entityType", "entityId", "metadata", "createdAt")
  VALUES (
    'audit_garage_backfill_20260520120100',
    'system',
    'general_settings.garage_backfill',
    'general_settings',
    COALESCE((SELECT "id" FROM "GeneralSettings" ORDER BY "createdAt" ASC LIMIT 1), 'general_default'),
    jsonb_build_object(
      'defaultFreeGarageSpots', default_free,
      'carsBackfilled',  (SELECT COUNT(*) FROM "GarageSpot" WHERE "id" LIKE 'gs\_bf\_%' ESCAPE '\'),
      'emptyBackfilled', (SELECT COUNT(*) FROM "GarageSpot" WHERE "id" LIKE 'gs\_bfempty\_%' ESCAPE '\')
    ),
    NOW()
  )
  ON CONFLICT ("id") DO NOTHING;
END $$;

-- Rollback notes
--   The forward migration is fully additive. To roll back:
--   1. DROP TABLE "GarageSpot";
--   2. ALTER TABLE "Product" DROP COLUMN "visibleInStore", DROP COLUMN "virtual";
--   3. ALTER TABLE "GeneralSettings" DROP COLUMN "defaultFreeGarageSpots";
--   4. DROP TYPE "GarageSpotTier";
--   5. DROP TYPE "GarageSpotSource";
--   6. Enum value adds ('virtual', 'virtual_complete') from the first migration file
--      CANNOT be rolled back without recreating the enums. To remove them, recreate
--      "FulfillmentMethod" and "FulfillmentStatus" without those values and re-cast
--      all columns. Do NOT roll back unless production has zero rows referencing them.
--   7. DELETE FROM "AdminAudit" WHERE "id" = 'audit_garage_backfill_20260520120100';
