export const caixaCopy = {
  header: { eyebrow: 'CAIXA DO MÊS' },
  cutoff: { prefix: 'Fecha em' },
  budget: {
    ofPlan: (total: string) => `de ${total}`,
    includedInPlan: (total: string) => `Incluso no plano ${total}`,
    overflow: (value: string) => `+${value} excedente`,
    toPay: 'A pagar',
  },
  summary: {
    catalogItems: (n: number) => `Itens do catálogo (${n})`,
    partners: (n: number) => `Parceiros (${n})`,
    includedInPlan: 'Incluído no plano',
    overflow: 'Excedente',
  },
  actions: {
    edit: 'Editar minha caixa',
    skip: 'Pular esse mês',
    resumePayment: 'Retomar pagamento',
    trackDelivery: 'Acompanhar entrega',
    retry: 'Tentar de novo',
    addAddress: 'Adicionar endereço',
  },
  skipped: { title: (month: string) => `Você pulou ${month}`, back: 'Voltar a montar' },
  awaiting: {
    banner: 'Aguardando pagamento',
    note: 'Sem pagamento até o corte, enviamos só os itens do budget.',
    comingSoon: 'Pagamento pelo app disponível em breve.',
  },
  notOpen: {
    title: 'Sem caixa neste ciclo',
    body: 'Volte quando o próximo ciclo abrir.',
  },
  ready: { banner: 'Caixa confirmada' },
  postCutoff: {
    closedOn: (date: string) => `Caixa fechada em ${date}`,
    note: 'Os extras não foram pagos a tempo, então enviamos só o que cabe no budget. Nada foi cobrado.',
    sent: 'ENVIADO',
    removed: 'REMOVIDO NO FECHAMENTO',
  },
  skipSheet: {
    title: (month: string) => `Pular a caixa de ${month}?`,
    body: 'Você pode voltar a montar enquanto houver tempo antes do corte.',
    confirm: 'Pular esse mês',
    cancel: 'Continuar montando',
  },
  history: {
    title: 'Histórico de caixas',
    current: 'Ciclo atual',
    status: {
      open: 'Em montagem',
      awaiting_payment: 'Aguardando pagamento',
      ready: 'Confirmada',
      skipped: 'Pulada',
      cancelled: 'Cancelada',
    },
    empty: { title: 'Nenhuma caixa ainda', body: 'Seu histórico aparece aqui a cada ciclo.' },
  },
  preferences: {
    title: 'Preferências',
    autoSend: 'Enviar automaticamente no corte',
    autoSendHint: 'No corte, enviamos sua caixa dentro do budget sem você precisar confirmar.',
    address: 'Endereço de entrega',
    changeAddress: 'Trocar',
    defaultAddressBadge: 'Padrão',
    save: 'Salvar',
    saving: 'Salvando...',
    saved: 'Preferências salvas.',
    saveError: 'Não foi possível salvar. Tente de novo.',
    addressInvalid: 'Endereço inválido. Escolha outro endereço.',
    locked: {
      title: 'Caixa travada',
      body: 'As preferências só podem ser alteradas enquanto a caixa está em montagem.',
    },
  },
  empty: {
    catalog: { title: 'Catálogo em curadoria', body: 'Novos itens aparecem aqui em breve.' },
    noAddress: {
      title: 'Sem endereço de entrega',
      body: 'Adicione um endereço para confirmar a caixa.',
    },
  },
  offline: { banner: 'Você está offline. Alterações não são salvas.' },
  loadError: { title: 'Não foi possível carregar', body: 'Verifique sua conexão e tente de novo.' },
  builder: {
    title: 'Montar a caixa',
    all: 'Todos',
    remaining: (value: string) => `restam ${value}`,
    add: 'Adicionar',
    soldOut: 'ESGOTADO',
    soldOutButton: 'Sem estoque',
    overflowBanner: (value: string) =>
      `Você passou do budget. O excedente de ${value} é cobrado à parte antes do fechamento.`,
    extraTag: 'EXTRA',
    withinBudget: (n: number) => `${n} ${n === 1 ? 'item' : 'itens'} · dentro do budget`,
    noExtraCharge: 'Sem cobrança extra',
    reviewCta: 'Revisar e confirmar',
    writeError: 'Não foi possível salvar. Tente de novo.',
    soon: 'Em breve',
    continueCta: 'Continuar',
  },
  partners: {
    title: 'Parceiros',
    banner: 'Módulos de parceiro são sempre cobrados à parte, fora do budget do plano.',
    inBox: 'Na caixa · cobrado à parte',
    add: 'Adicionar à caixa',
    reviewCta: 'Revisar e confirmar',
    empty: {
      title: 'Sem parceiros neste ciclo',
      body: 'Nenhum módulo de parceiro disponível agora. Você já pode revisar.',
    },
  },
} as const;
